### ISSUE TITLE
tooltips with full citation for visualization app

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab2#1]
perhaps using plotly for ggplot

ideally all points in viz app would be identifiable via tooltip. 

some other interactivity may be possible if we switch to plotly.

**Comment by amsan7** [comment]
i was able to use ggplotly on scatter / violin plot (not funnel) and i didn't think citation feature was necessary for forest plot

**Comment by mllewis** [comment]
The tooltips look awesome! Thanks for putting that together. Two minor thoughts: is it possible to cut the "short_cite" prefix and the "trace" legend?

**Comment by mllewis** [comment]
Doh...ditto Mike's comment...

**Comment by amsan7** [comment]
haha yeah, i'm looking into it!
