### ISSUE TITLE
negative d_var_calc?

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab2#105]
Some calculated variances seem negative, wanted to flag this for further investigation.

**Comment by cissard** [comment]
Can you specify the datasets that have this issue?

**Comment by christinabergmann** [comment]
I think I found it, it's in StatSeg in a Hay & Saffran entry, one of them has an impossible correlation over 1, so I am removing the correlation value. This fixes the issue. 

Follow-up: We need to implement checks for correlations provided (eg by authors).

**Comment by erikriverson** [comment]
@christinabergmann could this be another check we do when validating the data, and reporting if there is an invalid correlation value? I will add it to the checks if so.

**Comment by christinabergmann** [comment]
These values are calculated but indeed, there can be a check whether the calculation makes sense. But first, I need to further track whether (1) this still happens and (2) it's not an error in our math. 
I'll update with affected datasets

**Comment by erikriverson** [comment]
check 'r' column for [0-1]

**Comment by saraelshawa** [comment]
fixed in metalabr package
