### ISSUE TITLE
should we eliminate the meta-analytic model selector?

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab2#11]
since we think A) no MA in the dataset licenses a fixed effects model, and B) study grouping always is the right thing to do, why don't we simply eliminate the options to use RM and FE options, and that will simplify the interface.

**Comment by mcfrank** [comment]
if we think this is good, we need to write some text about it on the `statistical models` tab of the documentation page. right now we say you can't get r2 from it and you can't do funnel plot asymmetry but we don't have those in here anyway.

**Comment by christinabergmann** [comment]
Agreed, but we should also add a nested effect for the infants (this requires us to fix same_infant) and have different defaults depending on the MA, I think. @shotsuji knows much better though.

**Comment by shotsuji** [comment]
@christinabergmann, agreed, see related issue we opened "nesting structure for MA model".
