### ISSUE TITLE
Footer link to FAQ broken

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab2#111]
The footer on the website leads to a non-existent FAQ page: http://metalab.stanford.edu/faq#what-is-the-license-for-derivative-works-from-wordbank-e.g.-graphs-generated-by-the-site

Can we copy the content from wordbank and create the corresponding site?

**Comment by cissard** [comment]
I am going to adapt [this page from word bank](http://wordbank.stanford.edu/faq#what-is-the-license-for-derivative-works-from-wordbank-e.g.-graphs-generated-by-the-site), and send it to the team to get your feedback and modifications before creating the webpage.

**Comment by erikriverson** [comment]
Fixed in latest deploy
