### ISSUE TITLE
simple arithmetic MA doesn't appear on the website

### ISSUE THREAD

**Issue by cissard** [langcog/metalab2#112]
Hi,

I'm scanning through the [data spreadsheet](https://docs.google.com/spreadsheets/d/18JSxBB5GK87JqJ89aH055M5MaITY1qRqvZAJXBm3t-M/edit#gid=0) and I see that some line don't have any t or SD, so I guess it relates to [this older issue](https://github.com/langcog/metalab2/issues/96).
However they all have d, and I see in compute_es.R that d_calc takes d if its present.  

Does anyone have any other idea about why this MA doesn't appear?

Cécile

**Comment by kylehamilton** [comment]
I think I found the problem when running main_builder.R there is an error that pops up for the simple arithmetic data.
```R
Dataset 'Simple arithmetic competences' has invalid value 'eye_tracking' for field 'response_mode'.
Dataset 'Simple arithmetic competences' had one or more validation issues, not being cached.
```
I went to the Google spreadsheet and found a typo in the response_mode variable on the first row of data the Wynn (1992) study. https://docs.google.com/spreadsheets/d/18JSxBB5GK87JqJ89aH055M5MaITY1qRqvZAJXBm3t-M/edit#gid=0&range=J2 

MetaLab expects to see eye-tracking not eye_tracking. Within the response_mode definition found in spec.yaml at line 65 there is eye-tracking but not eye_tracking. If someone with access to that file can correct it then it should work and load into MetaLab. 
https://github.com/langcog/metalab2/blob/674af269a0ab17c5d29317be8064c6b4c909a9d4/metadata/spec.yaml#L65-L75

**Comment by shotsuji** [comment]
Thanks for troubleshooting - I corrected the typo, and I will also give you access to the Metalab google drive folder. It contains various things; the datasets are in the "Tabular data from meta-analyses" folder.

**Comment by kylehamilton** [comment]
Ok I think that did it. When running main_builder I now get this message and the visualization app now displays the data.
```R
Dataset 'Simple arithmetic competences' saved successfully.
```
![image](https://user-images.githubusercontent.com/2274317/56474579-97d46e00-6430-11e9-83db-64f8fda600e6.png)
