### ISSUE TITLE
Allow access to specific versions of datasets

### ISSUE THREAD

**Issue by cissard** [langcog/metalab2#114]
Following [Issue #102 ](https://github.com/langcog/metalab2/issues/102), it might be great to be able to call specific versions of each dataset. Maybe through a drop-down menu?

**Comment by alecristia** [comment]
(or perhaps it is time to start thinking about APIs -- whereby people can call on versioned datasets and versioned code)

**Comment by christinabergmann** [comment]
Isn't this the same as #102?
