### ISSUE TITLE
approximation of mean age in Quinn & Kidd (2018)

### ISSUE THREAD

**Issue by cissard** [langcog/metalab2#119]
Quinn & Kidd coded the age range of each group instead of the mean ages. To approximate the mean age, Sho and I have decided to take the middle of each age range. Let me know if you disagree with this solution before next week, or I will close the issue.

**Comment by shotsuji** [comment]
We also thought about adding a "comments" bullet point to the dataset description section so people see these kinds of particularities immediately

**Comment by christinabergmann** [comment]
I like the comment option, sounds good
Could also contain eg "Is not systematic" or "Additional information on this website" ?

**Comment by cissard** [comment]
Yes I added "age is not systematic but the middle of the age range provided in the supplementary materials" in the comment section for Quinn et al. MA.
 I guess it relates to issue #117 about adding a link to PRISMA flowchart, that could go in the comments too.
