### ISSUE TITLE
Set formatting of CSV files in /data

### ISSUE THREAD

**Issue by kylehamilton** [langcog/metalab2#126]
When building MetaLab the software updates data from Google Sheets which throws up minor formatting differences. This is related to #124, I'll take a look at this and see if I can fix it. It's not a major problem right now. 

![image](https://user-images.githubusercontent.com/2274317/56446059-4eabdf00-62b5-11e9-80a0-f6ade34a1143.png)

**Comment by erikriverson** [comment]
/data is no longer checked into repo , so I do not believe this is relevant anymore, closing. will re-open if needed.
