### ISSUE TITLE
visualization app - should we use Hedges g by default? 

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab2#13]
Relatedly, would it be useful to eliminate some options from this selector? Or alternatively force different defaults for different MAs? For example, we might want most MAs to default to g but then have a few that default r (the correlational ones)? 

Maybe we can get rid of z as well. 

Comments welcome.

**Comment by christinabergmann** [comment]
Great points, is z useful for any MA?
Defaults could be domain specific (r in the individual diffs domain [I do remember talks about making a separate domain for those] makes a lot of sense, but not much elsewhere), but having all used ones in there as options might be nice. 

In short: remove z, make g default, leave d and r, and make r default for pointing.

**Comment by christinabergmann** [comment]
For now:

- [ ] remove z
- [ ] change default to g

Later on: 

- [ ] Add sth to spec to opt for diff defaults?

**Comment by amsan7** [comment]
@christinabergmann removed z and changed default. did you want to add something to spec for this release or after?

**Comment by christinabergmann** [comment]
That's for after, thanks!!
