### ISSUE TITLE
remove "trace N" legend item

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab2#14]
in plotly apps - should just be able to suppress legend maybe?

**Comment by mcfrank** [comment]
and maybe also the "short_cite: " in the tooltips (but adding the experiment number) for the age scatter.

**Comment by christinabergmann** [comment]
Now it would be good to have legends for the moderator effects. Also, "short_cite" still there.

**Comment by amsan7** [comment]
@christinabergmann did you want to create another issue for the moderator effect legend? closing this one as trace N legend and short_cite are now gone
