### ISSUE TITLE
testing before deployment

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab2#141]
We need to figure out a way to make sure that the site stays live as we update data - this means something like a sandbox or dev server plus a defined deployment workflow. It may also mean moving to fork & pull for changes to master.

**Comment by kylehamilton** [comment]
We can set up a sandbox environment on the server, for now, I'll take a look at this tonight but I don't think it'll be a problem. I have a similar set up for my Shiny apps on my server.

**Comment by christinabergmann** [comment]
Great, everyone. This sounds like a good proposal. It seems reasonable to me to limit direct push access anyhow.
We might just need to think about an update cycle procedure (i.e. regular checks to merge) that is sustainable in the long run.

**Comment by erikriverson** [comment]
There is now a staging server for shiny apps at http://52.24.141.166:4848/
