### ISSUE TITLE
Pages currently not working

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab2#142]
A quick summary which parts of the site don't work as of right now:
http://metalab.stanford.edu/about.html
http://metalab.stanford.edu/publications.html
http://metalab.stanford.edu/tutorials.html
http://metalab.stanford.edu/documentation.html

(i.e. all except the main page and analyses)

On Analyses, the following are down:
http://metalab.stanford.edu/reports/ChildDevPaper.html and all other reports (it worked a day or two ago, weird)

**Comment by mcfrank** [comment]
there is some issue in rendering the reports on our instance, it was
running out of resources yesterday. but today it worked!

re: paper

Quitting from lines 9-17 (ChildDevPaper.Rmd)


package or namespace load failed for 'tidyverse' in loadNamespace(j <-
i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):

 namespace 'tidyr' 0.7.0 is already loaded, but >= 0.7.2 is required

**Comment by christinabergmann** [comment]
OK all other pages seem to be back, just in time for my 2nd talk!
