### ISSUE TITLE
Empty visualization when adding new method

### ISSUE THREAD

**Issue by cissard** [langcog/metalab2#146]

**Comment by cissard** [comment]
I added a new field in the method section of the spec.yaml file to fit with the Symbolic play dataset, but when I run the visualization app locally it's empty (see the attached screen capture). 
![Capture d’écran 2019-06-12 à 14 43 33](https://user-images.githubusercontent.com/32436707/59352253-81f07480-8d20-11e9-9ece-8a31bcb7eb0c.png)
The main_builder script runs much faster but creates the data files and doesn't produce any error message. However when I run the visualization app I get:
Warning: Error in eval: object 'all_data' not found

I thought it came from the fact that I had initially named the new method "other", but I still have the same problem with other names. When I remove the method option it goes back to normal.

**Comment by erikriverson** [comment]
this has been fixed with latest commit , added 'obeservational' as an option for the 'method' column
