### ISSUE TITLE
new study-specific columns not added

### ISSUE THREAD

**Issue by cissard** [langcog/metalab2#152]
Hello,

I noticed that the study-specific variables, usually added as the last columns in the csv files, are not added for the cross-situational word learning and natural speech preference datasets. For the cross-situational word learning dataset, the variables that were added earlier in the past are there, but not the recent ones (added by the curator a couple of weeks ago). 

Could it be that there is a maximum number of columns that can be in the csv files? Or is there something limiting the number of columns in the data csv files, e.g. a maximum file size (as all dataset files include all variables from all datasets maybe we reached a max with all the new MA)?

**Comment by christinabergmann** [comment]
Only columns specified in the metadata are added, so the first step would be to check all metadata.

**Comment by cissard** [comment]
Hi Christina,

I did checked the metadata files. I noticed this as some moderators that I had specified for my MA in the metadata did not appear. Then I saw that the same problem occured for the cross-situational word learning MA.

**Comment by mllewis** [comment]
The columns have to be specified in both `datasets.yaml` AND `spec.yaml'.  The ones that aren't appearing are probably the ones not in the spec file.

**Comment by erikriverson** [comment]
This is fixed with latest deploy
