### ISSUE TITLE
MAs not shown on domain page

### ISSUE THREAD

**Issue by RodrigoDalBen** [langcog/metalab2#157]
Hi there, 

"Symbolic play", "Natural speech preference", and "Cross-situational word learning" are not being displayed at http://metalab.stanford.edu/domain/early_language.html 

https://github.com/langcog/metalab2/blob/3ac44bf24a05df860febfb6054bbff3228abbd46/metadata/datasets.yaml#L552-L625

**Comment by erikriverson** [comment]
@RodrigoDalBen Thank you for the report! "Natural speech preference", and "Cross-situational word learning" should be there on the next deploy, and I'll update here when that's done. 

The Symbolic Play dataset has a validation issue when trying to load it: `Dataset 'Symbolic play' has invalid value 'observational' for field 'method'.` I will followup with team on how to remedy that.

**Comment by erikriverson** [comment]
Symbolic play now shown with latest deploy
