### ISSUE TITLE
fix p value labels on funnel plot 

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab2#16]
or maybe get rid of these and mark them in the legend instead. (sho has added this to the google doc).

**Comment by amsan7** [comment]
@shotsuji could you point me to google doc again? for this issue, if i remember correctly, we wanted to remove the p-value text embedded in the funnel plot and put it in the help text.. but not sure

**Comment by shotsuji** [comment]
You remember correctly!
here's the link: https://docs.google.com/document/d/10v6KdtVXRKtAKZWTX85ZkFdXSbGMUEI1dUhf1El-q9I/edit

or, here's the relevant text directly: Studies with high precision should be close to the average, while studies with low precision can be spread evenly on both sides of the average when there is no publication bias. An asymmetric shape can be an indicator of publication bias. Shaded regions show p <.05 and p <.01 regions, respectively.

**Comment by amsan7** [comment]
ah, thanks for the doc! ok, this should be fixed, closing this issue :)
