### ISSUE TITLE
modify thumbnails for domains

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab2#21]
boring candidate for early language – waveform: https://commons.wikimedia.org/wiki/File:Signal-speech-martin-de.png

we need help here, what should we have for logos for the domains?

**Comment by mcfrank** [comment]
or use icons like the ones here: https://langcog.github.io/PAQ/

(sho says she will try her hand at this)

**Comment by shotsuji** [comment]
With Christinas feedback, done! I just went ahead and replaced them in images/domains - if anyone wants further adjustments let me know.

**Comment by christinabergmann** [comment]
OK closing now, nobody objected :)
