### ISSUE TITLE
reports are super out of date

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab2#24]
@mllewis and @christinabergmann and @shotsuji - can you update these?

**Comment by shotsuji** [comment]
I updated hierarchical random effects report.
For the others - remember to remove the passage about "re-rendering nightly" from the header!

**Comment by christinabergmann** [comment]
Not sure what to adapt about developmental curves apart from the disclaimer.
Removed p-curves for now bc we are still discussing them and it might be nice to have them as app.

**Comment by shotsuji** [comment]
Mostly this was based on the report headers who showed a very old date.
However it WOULD be nice if they were automatically re-rendered from time to time. Why did we abandon that system again?

**Comment by christinabergmann** [comment]
Ah ok, then the main issue is solved. 
Would be good to have: "last updated on [date]" then, I guess @amsan7 knows more. :)

**Comment by amsan7** [comment]
just catching up here - is the issue resolved? w respect to headers being out of date, the hierarchical random effects report correctly displays "This report was rendered on 2017-12-24." Also, it seems like the reports do re-render daily.

**Comment by shotsuji** [comment]
@amsan7 if the reports re-render daily and the header date changes accordingly this should be resolved :)
