### ISSUE TITLE
updates to about page

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab2#28]
- [x] add @amsan7 
- [x] put mika as former member 
- [x] confirming former member for page as well (@shotsuji will confirm)
- [x] add some implementation details (github pages + shiny server) under source code, and credit @daattali and AttaliTech for redesign - Dean, can you tell us what kind of attribution you want here? 
- [x] under funding thank RStudio for their education license of Shiny Server Pro

**Comment by daattali** [comment]
Any mention of AttaliTech Ltd would be fantastic, with a link would be even
nicer. But I'm not expecting this, it's 100% ok if you omit any credits
since it was paid
