### ISSUE TITLE
provide some documentation for viz and power apps

### ISSUE THREAD

**Issue by mcfrank** [langcog/metalab2#3]
either these could be separate documentation tabs (heavier weight) or else could be question marks by each of the plots with a short sentence about each option. also tooltips on pulldowns (like on wordbank). 

@mollyllewis or @chbergma could you help @amsan7 with text for this once the shiny apps are up and running?

**Comment by christinabergmann** [comment]
Happy to, I like the idea of question marks for short bits of text!
