### ISSUE TITLE
Add contribute page in documentation

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab2#32]
It's announced and not present, so would be good to have some quick instructions how to contribute. Cecile might help with that?

**Comment by shotsuji** [comment]
I'll email Alex & Cecile suggesting a github account for her!

**Comment by christinabergmann** [comment]
Made a first page, @cissard could expand if needed.

**Comment by cissard** [comment]
I just added a reference to the tutorial on how to edit existing MA in the MetaLab format.

**Comment by christinabergmann** [comment]
Hm, strangely enough it's still not in the documentation.
