### ISSUE TITLE
Add Cecile to github

### ISSUE THREAD

**Issue by shotsuji** [langcog/metalab2#33]
Hi @mcfrank can you please give Cecile access to the repo? https://github.com/cissard @cissard
Thank you!

**Comment by amsan7** [comment]
done!

**Comment by shotsuji** [comment]
Hi, actually @alecristia also needs to be added - and I do not seem to have the rights to see settings (and add someone at least at a collaborator) - can that be fixed for everyone concerned as well? Thanks :)

**Comment by cissard** [comment]
Thanks !
