### ISSUE TITLE
tutorials don't render

### ISSUE THREAD

**Issue by cissard** [langcog/metalab2#37]
The tutorials are not updated on the new website. I checked the [.../metadata/tutorials.yaml](https://github.com/langcog/metalab2/blob/master/metadata/tutorials.yaml) page, the new tutorials are specified.

**Comment by daattali** [comment]
Not sure. I tried adding new tutorials when testing and didn't notice any problems but that was a few months ago. I see there's a long history of changes to the tutorials yaml, have none of the changes to it ever worked? Perhaps check the build error log to see if there's anything there. I kept a test environment for a couple months but recently deleted it so it'll be hard for me to help test/debug now

**Comment by cissard** [comment]
Thanks for your quick reply! It seems to be a more general problem as I other changes that I made don't render either. I will look if it's related to bad setup I made with my account. Maybe I have to make a pull request and not only commits within the repo?

I know you're not responsible anymore so I will ask the current members. Thank you very much !

**Comment by shotsuji** [comment]
Hi. I think updates are rendered once a day - I know that your and my previous recent tutorial changes were rendered ok, so maybe we just need to wait for a few hours.

**Comment by cissard** [comment]
Thanks Sho! I will look up tomorrow!

**Comment by daattali** [comment]
Ah yes - so did all the previous changes to the tutorial page DID work? If you look at https://github.com/langcog/metalab2/tree/gh-pages you'll see it gets rendered once a day, I believe it's at midnight UTC. It's automated by a crontask , as you can see in the README. I think in 4.5 hours will be the next automated render.

**Comment by shotsuji** [comment]
Yeah looks to me as if they rendered fine before. Thanks Dean, it's good to know the time-point of rendering.

Cecile - if you still don't see the right updates tmr could you then tell me what exactly is missing (just because you mentioned you don't see my updates rendered, but I do see them)? TTY tmr!

**Comment by cissard** [comment]
Yes some of them, and I just realized that I included the other ones in the yaml file only today. So sorry, my mistake.

@shotsuji yes now I see your update. I'll tell you tomorrow about today's updates.

**Comment by christinabergmann** [comment]
I think this is solved, right?

**Comment by shotsuji** [comment]
yes!
