### ISSUE TITLE
tutorials: remove the link to the youtube playlist

### ISSUE THREAD

**Issue by cissard** [langcog/metalab2#38]
As the new tutorials include embedded videos maybe it's redunndant to have the link to the youtube playlist at the top of the [tutorials main page](https://langcog.github.io/metalab2/tutorials.html)? If yes I can modify the code.

**Comment by shotsuji** [comment]
agreed! great if you can modify that

**Comment by cissard** [comment]
I modified the code, I will check tomorrow the render.

**Comment by christinabergmann** [comment]
Good point, and looks like removing worked.
