### ISSUE TITLE
Add curator definition to documentation

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab2#53]
Responsibilities of a curator:
- executive decisions regarding spreadsheet content
- determines moderators to be displayed
- update data
- verify and correct if needed
- ...

**Comment by cissard** [comment]
added to the documentation in the contribute tab.

**Comment by christinabergmann** [comment]
Great, should we schedule this annual curator mail with all curator names to the metalab mailing list? Should be possible, right?

**Comment by cissard** [comment]
The changes don't render on the website.
