### ISSUE TITLE
Add instructions on how to export and work with the data

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab2#62]
In the documentation, add a page on how to use the metalab data to:
1. calculate power
2. conduct custom analyses (eg with subsets by language or methods)
3. other use cases we have come across

Also add how to download the data (via visualization and dataset page) and give instruction how to set "." as decimal separator and "," as table separator when users want to use excel, open office, or similar programs. 

Assigning @cissard, remove yourself if that's wrong :)

**Comment by cissard** [comment]
Hi Christina,

I am not sure of what to write for the first 3 points. Are you thinking of something like what Alex wrote [there](https://sites.google.com/site/inphondb/what-can-you-do-with-inphondb), like in the 2nd par. of section 1.3 for power or in section 3 for custom analyses?

Best,

Cécile

**Comment by christinabergmann** [comment]
Yes, those instructions by Sho are a really good start!

**Comment by cissard** [comment]
Here is a [first draft](https://docs.google.com/document/d/1zPSg-EAYTFQp9IDd8ysmsHH8r58X-PGYPqTUxj-p0Cs/edit), let me know what you think!

**Comment by cissard** [comment]
Hi Christina,

Can you go through the document and tell me if it's okay for you? I would like to finish this up if possible.

**Comment by christinabergmann** [comment]
As I commented, I think video vignettes are a good idea, otherwise I responded to all open comments just now.

**Comment by cissard** [comment]
Ok, so should we wait for the video vignettes to be ready?

**Comment by cissard** [comment]
I just added a new tab for this in the (https://langcog.github.io/metalab2/documentation.html)[documentation section].

**Comment by christinabergmann** [comment]
Page not found: http://metalab.stanford.edu/documentation.html

**Comment by cissard** [comment]
I changed the extension from .md to .Rmd, it should work when the site is updated.
