### ISSUE TITLE
Add a box about the challenge on the home page

### ISSUE THREAD

**Issue by cissard** [langcog/metalab2#63]
Add a box containing  [this info](https://docs.google.com/document/d/1IP7YfpWxT0ntD7a4UiQyBgkML9buXM8m3wgQiayN_L4/edit) to grab people interest about the challenge and get more submissions.

**Comment by amsan7** [comment]
i put it at the bottom of the page

**Comment by cissard** [comment]
Hi Alessandro,

Would it be possible to have a similar design as the "early language" and "cognitive development" boxes? i.e. with a thin black rectangle around and a white background, and "Challenge" as the title of the box in the same height and font as "early language" and "cognitive development". 

Also finally Alex and I thought that it would be better to only have one sentence on the home page and link to a page under the tutorials section of the website. Can you please only put the following on the home page: "To celebrate the release of the new website, the MetaLab team with support of the Berkeley Initiative for Transparency in the Social Sciences (BITSS) is organizing a challenge for authors of meta-analyses on cognitive development. Read more [here](link to a new page under the tutorials section)". Then the new page would contain [this info](https://docs.google.com/document/d/1IP7YfpWxT0ntD7a4UiQyBgkML9buXM8m3wgQiayN_L4/edit).

Sorry for the change...

**Comment by amsan7** [comment]
what do you mean by the "NEWS" red box? so we want 2 boxes, one of them only saying "NEWS"?

also, that link doesn't appear to be available to the public, can you send a different one?

**Comment by cissard** [comment]
About the link I was thinking about a new tab in the turorials section. I created a new Rmd file in the tutorials folder of the github repo. Will it create the new tab automatically or do I have to do something else? 

About the box yes that would be two boxes with the one saying NEWS on top of the other (See the schema).


![capture d ecran 2018-05-09 a 12 27 32](https://user-images.githubusercontent.com/32436707/39810195-6d089b82-5384-11e8-9ef4-e80e2a970fee.png)

**Comment by amsan7** [comment]
how does it look now? metalab.stanford.edu

**Comment by cissard** [comment]
Hi Alessandro,

I think it looks great! Thank you very much for the changes!
