### ISSUE TITLE
Add DOI column?

### ISSUE THREAD

**Issue by shotsuji** [langcog/metalab2#64]
Hi,
I've started that with new entries - would we want to add a column "doi" to all datasets?
Sho

**Comment by christinabergmann** [comment]
I like it, I used to do it for InWordDB, too, and it makes finding the source paper much easier.

**Comment by christinabergmann** [comment]
Another advantage would be that we can check for retractions this way. Peder Isager found this package: https://github.com/Ironholds/retractr

I assume because the issue remains open that Cecile didn't get around to doing this. Might be another good first task for an incoming data manager.

**Comment by mllewis** [comment]
I think we should definitely do this. I did some analyses awhile ago on citations networks from metalab and hunted down dois for a lot of the papers - they're in a csv here: https://github.com/langcog/metalab/blob/master/reports/networks/dois2.csv 

They're relatively easy to get from the citation here: https://apps.crossref.org/SimpleTextQuery/

**Comment by mllewis** [comment]
Just to follow up on this...I've written some code that uses the RefManageR package in R as an api to get the dois and bibtex references automatically.  The look-up is noisy so it still requires someone to go through them one by one and check if they're right, but it definitely speeds up the process. If someone is going to do work on this, let me know, and I'll point you to my code.
