### ISSUE TITLE
MetaLab talk from BITSS on website?

### ISSUE THREAD

**Issue by shotsuji** [langcog/metalab2#78]
I just was told that our BITSS talk exists as a video on Youtube - what do you think of linking it somewhere on the website?
https://www.youtube.com/watch?v=lD7TccGEZjo&list=PLAKyhL4GNnqM0o8sdISIMP_38imdkHtVj&index=9

**Comment by mcfrank** [comment]
Great!
Mike

**Comment by amsan7** [comment]
added to Documentation -> Overview
