### ISSUE TITLE
Switch dataset / keeping track of automatic versus hand-coded looking times

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab2#90]
I am fixing a bunch of issues in the switch dataset and saw that it codes "oculomotor" as response mode for eye tracking (changing that now). Elsewhere this is usually as behavioral. This brings also back the question how / if we want to distinguish human-coded from automatically coded eye movement data. 

From the main_builder.R output:
Dataset 'Switch Task' has wrong type for numeric field 'expt_num'.
Dataset 'Switch Task' has invalid value 'oculomotor' for field 'response_mode'.
Dataset 'Switch Task' has invalid value 'Central fixation' for field 'method'.
Dataset 'Switch Task' has invalid value 'looking time' for field 'dependent_measure'.
Dataset 'Switch Task' has wrong type for numeric field 't'.
Dataset 'Switch Task' has wrong type for numeric field 'd'.
Dataset 'Switch Task' has wrong type for numeric field 'd_var'.
Dataset 'Switch Task' had one or more validation issues, not being cached.

**Comment by shotsuji** [comment]
I'd like making that distinction actually, and it will also interest people.
Will require some recoding --> intern or new data manager?

**Comment by christinabergmann** [comment]
good question, might be a second good task for a datamanager, along with adding datasets and DOIs. :)

**Comment by christinabergmann** [comment]
@cissard A bunch of the issues (t, d, d_var) come from the wrong (French?) data format, can you check whether the original submission has '.' as decimal separator?

**Comment by christinabergmann** [comment]
Another issue: Bilingual infants are coded as typical, not bilingual

**Comment by cissard** [comment]
Thanks Christina!
Le 14 août 2018 à 14:19, Christina Bergmann <notifications@github.com<mailto:notifications@github.com>> a écrit :


OK, most issues should be solved now. FYI, google sheets also has local settings (under spreadsheet settings) and adjusting those did the trick. This might be useful if the same problem occurs with other datasets.
