### ISSUE TITLE
No gh-pages update

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab2#94]
Switch task (a challenge dataset) should be compatible now, but because the site hasn't been updated in 9 days, it doesn't appear. @amsan7, any ideas?

**Comment by amsan7** [comment]
ok, should be updated now. i also made it so that when the rendering fails, the shiny apps won't go down... hopefully those are always up now

**Comment by christinabergmann** [comment]
Amazing, thank you!!!
