### ISSUE TITLE
Metalab website not updated in several days (or more)

### ISSUE THREAD

**Issue by juliacarbajal** [langcog/metalab2#99]
Last Friday I made some changes to the repo and it's been 5 days but I still don't see the changes appearing in the website. With Alex we checked the reports pages (e.g. the Hierarchical random effects report), which at the top of the page contain a "Last updated on `r Sys.Date()`." line. If I understand correctly, the `r Sys.Date()` date is normally regenerated every time the website updates, but in these pages the date reads 2018-09-26. So I suspect the website hasn't updated since September. Does anybody know how to solve this problem?

**Comment by christinabergmann** [comment]
cc @amsan7

**Comment by mcfrank** [comment]
Hi all,

We don't have an "auto-pull" feature on the site right now. We've found
that this leads to massive instability because people push datasets and
break the site. So now it takes someone to log in to AWS and refresh.

Mike

**Comment by christinabergmann** [comment]
OK, who apart from Alessandro could do that? And would it make sense to "initiate" more people?

**Comment by amsan7** [comment]
just refreshed the site

**Comment by juliacarbajal** [comment]
I would find it useful to be able to do this myself as I'm currently working on fixing bugs and other issues, but I understand if you prefer to have only permanent members of metalab doing this. In that case I would like to know who I should address when the website needs refreshing (for example, I just made another change to fix a bug a couple hours ago so it needs refreshing again).

**Comment by cissard** [comment]
Hi,

Can someone refresh the site now? I made some changes on the about page. 

Cécile

**Comment by christinabergmann** [comment]
I think apart from @mcfrank nobody has been "initiated"... Might be good to create internal documentation for 1-2 permanent members so we can distribute this task?

**Comment by amsan7** [comment]
hi all, i updated the website, and for future reference @benjamindemayo also know how to update it!

**Comment by cissard** [comment]
Thanks Alessandro!

**Comment by cissard** [comment]
The [documentation page](http://metalab.stanford.edu/documentation.html) raises a 404 error. I think that's because I incorrectly used a .md extension. I changed it to .Rmd. @benjamindemayo can you please update the website again?

**Comment by erikriverson** [comment]
New MetaLab deploy procedure uses Github Actions when PR made to main branch (staging), and merged into main branch (prod). any errors in the build can be seen from the Actions result.
